package fr.ynov.dap.dap.data;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 *
 * @author David_tepoche
 *
 */
@Entity
public class AppUser {
    /**
     * dunno.
     */
    @Id
    @GeneratedValue
    private Integer id;
    /**
     * dunno.
     */
    @Column
    private String userKey;

    /**
     * dunno.
     */
    @JsonManagedReference
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "owner")
    private List<GoogleAccount> accounts;

    /**
     * @return the accounts
     */
    public List<GoogleAccount> getAccounts() {
        return accounts;
    }

    /**
     * @return the userKey
     */
    public String getUserKey() {
        return userKey;
    }

    /**
     * @param usrKey the userKey to set
     */
    public void setUserKey(final String usrKey) {
        this.userKey = usrKey;
    }

    /**
     * @return the id
     */
    public Integer getId() {
        return id;
    }

    /**
     * @param idAutoGenerated the id to set
     */
    public void setId(final Integer idAutoGenerated) {
        this.id = idAutoGenerated;
    }

    /**
     * save googleAccount and tje link between them.
     *
     * @param gAccount the google account that the userapp have
     */
    public void addGoogleAccount(final GoogleAccount gAccount) {
        gAccount.setOwner(this);
        this.getAccounts().add(gAccount);
    }

}
